language: go

os:
  - linux

go:
  - 1.12.x
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - $GOPATH/bin/goveralls -v -race -repotoken $COVERALLS_TOKEN
