language: go

os:
  - linux
  # - osx

matrix:
  allow_failures:
    - os: osx


go:
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge
  - go get -v ./...

script:
  - make testall
  - cp build/report.out coverage.txt

after_success:
  - $GOPATH/bin/goveralls -coverprofile=build/report.out -service=travis-ci
  - bash <(curl -s https://codecov.io/bash)
  - make clean