language: go

os:
  - linux

go:
  - 1.12.x
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - make fmt
  - make test
  - $GOPATH/bin/goveralls -coverprofile=build/cover.out -service=travis-ci -repotoken $COVERALLS_TOKEN
