/*
Package ppk - Public, Private Key

In this package we define Private and Public keys as generated by `curve25519`.
These keys will be used for AEK and node identification and key routing.

Keys are 32 byte long and can be represented as 64 char hex strings.
*/
package ppk // import "cpl.li/go/cryptor/crypt/ppk"

import (
	"crypto/subtle"
	"encoding/hex"
	"errors"
)

// KeySize is the size (in bytes) of both the public and private keys.
const KeySize = 32

type (
	// PrivateKey is a curve25519 point.
	PrivateKey [KeySize]byte

	// PublicKey is a curve25519 point, derived from the private key.
	PublicKey [KeySize]byte
)

func loadHexKey(src string, key []byte) error {
	// decode the string
	slice, err := hex.DecodeString(src)
	if err != nil {
		return err
	}

	// match with expected key size, return error if not matching
	if len(slice) != len(key) {
		return errors.New("hex string does not match key size")
	}

	// copy decoded string to key
	copy(key, slice)

	return nil
}

// ToHex returns the secret key as a hex string.
func (sk PrivateKey) ToHex() string {
	return hex.EncodeToString(sk[:])
}

// ToHex returns the public key as a hex string.
func (pk PublicKey) ToHex() string {
	return hex.EncodeToString(pk[:])
}

// FromHex loads a hex string as a secret key.
func (sk *PrivateKey) FromHex(src string) error {
	return loadHexKey(src, sk[:])
}

// FromHex loads a hex string as a public key.
func (pk *PublicKey) FromHex(src string) error {
	return loadHexKey(src, pk[:])
}

// Equals compares two private keys, returns true if equal, false if not.
func (sk PrivateKey) Equals(to PrivateKey) bool {
	return subtle.ConstantTimeCompare(sk[:], to[:]) == 1
}

// Equals compares two public keys, returns true if equal, false if not.
func (pk PublicKey) Equals(to PublicKey) bool {
	return subtle.ConstantTimeCompare(pk[:], to[:]) == 1
}

// IsZero checks the key against a zero key, returns true if all key bytes are 0.
func (sk PrivateKey) IsZero() bool {
	var zero PrivateKey
	return sk.Equals(zero)
}

// IsZero checks the key against a zero key, returns true if all key bytes are 0.
func (pk PublicKey) IsZero() bool {
	var zero PublicKey
	return pk.Equals(zero)
}
