name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          version: 1.12
        id: go

      - name: Checkout
        use: actions/checkout@master
        path: ${{ go.module-path }}

      - name: Get dependencies
        working-directory: ${{ go.module-path }}
        run: |
          go get -v -t -d ./...

      - name: Test
        working-directory: ${{ go.module-path }}
        run: make test

      - name: Check fmt
        working-directory: ${{ go.module-path }}
        run: make fmt
